/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnv_cs311b;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PC
 */
public class NhanVienGUI extends javax.swing.JFrame {

    private DSNhanVien ds = new DSNhanVien();
    DefaultTableModel dm = new DefaultTableModel();
    public NhanVienGUI() {
        initComponents();
        this.jTable1.setModel((TableModel) dm);
        String[] tenCot = {"Mã","Họ tên","Hệ số lương","Ngày vào","Phái","Công việc","Chức vụ","Phụ cấp chức vự"};
        dm.setColumnIdentifiers(tenCot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfmanhanvien = new javax.swing.JTextField();
        tfhoten = new javax.swing.JTextField();
        tfhesoluong = new javax.swing.JTextField();
        tfngayvaolam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfcongviec = new javax.swing.JTextField();
        tfchucvu = new javax.swing.JTextField();
        tfphucapchucvu = new javax.swing.JTextField();
        rbnam = new javax.swing.JRadioButton();
        rbnu = new javax.swing.JRadioButton();
        rbchuyenvien = new javax.swing.JRadioButton();
        rbcanboquanly = new javax.swing.JRadioButton();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoama = new javax.swing.JButton();
        btxoadong = new javax.swing.JButton();
        bttimma = new javax.swing.JButton();
        bttrungbinhluon = new javax.swing.JButton();
        bttimphai = new javax.swing.JButton();
        bttimmax = new javax.swing.JButton();
        bthienthi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã nhân viên:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Hệ số lương:");

        jLabel4.setText("Ngày vào làm:");

        jLabel5.setText("Phá:i");

        jLabel6.setText("Công việc:");

        jLabel7.setText("Chức vụ:");

        jLabel8.setText("Phụ cấp chức vụ: ");

        buttonGroup1.add(rbnam);
        rbnam.setText("Nam");

        buttonGroup1.add(rbnu);
        rbnu.setText("Nữ");
        rbnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnuActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbchuyenvien);
        rbchuyenvien.setText("Chuyên viên");

        buttonGroup2.add(rbcanboquanly);
        rbcanboquanly.setText("Cán bộ quản lý");

        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoama.setText("Xóa mã");
        btxoama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoamaActionPerformed(evt);
            }
        });

        btxoadong.setText("Xóa dòng");
        btxoadong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoadongActionPerformed(evt);
            }
        });

        bttimma.setText("Tìm mã");
        bttimma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimmaActionPerformed(evt);
            }
        });

        bttrungbinhluon.setText("Trung bình lương");
        bttrungbinhluon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttrungbinhluonActionPerformed(evt);
            }
        });

        bttimphai.setText("Tìm phái");
        bttimphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimphaiActionPerformed(evt);
            }
        });

        bttimmax.setText("Tìm max");
        bttimmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimmaxActionPerformed(evt);
            }
        });

        bthienthi.setText("Hiển thị");
        bthienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthienthiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btthem)
                            .addComponent(bttrungbinhluon))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfhoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfhesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbnam)
                                        .addGap(27, 27, 27)
                                        .addComponent(rbnu)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfphucapchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbchuyenvien)
                                        .addGap(28, 28, 28)
                                        .addComponent(rbcanboquanly))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bttimphai)
                                        .addGap(92, 92, 92)
                                        .addComponent(bttimmax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btsua)
                                        .addGap(132, 132, 132)
                                        .addComponent(btxoama)))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btxoadong)
                                    .addComponent(bthienthi))
                                .addGap(106, 106, 106)
                                .addComponent(bttimma)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfhesoluong, tfhoten, tfmanhanvien, tfngayvaolam});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfchucvu, tfcongviec, tfphucapchucvu});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfhoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfhesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbnam)
                            .addComponent(rbnu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfphucapchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbchuyenvien)
                            .addComponent(rbcanboquanly))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btxoama)
                    .addComponent(btxoadong)
                    .addComponent(bttimma)
                    .addComponent(btsua))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttrungbinhluon)
                    .addComponent(bttimphai)
                    .addComponent(bttimmax)
                    .addComponent(bthienthi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnuActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        String ma = this.tfmanhanvien.getText();
        String ht = this.tfhoten.getText();
        double hsl = Double.parseDouble(this.tfhesoluong.getText());
        Date nvl = new Date();
        DateFormat df = new SimpleDateFormat ("yyyy/m/d");
         try {
             nvl = df.parse(this.tfngayvaolam.getText());
         } catch (ParseException ex) {}
         boolean phai = true;
         if (this.rbnam.isSelected())
             phai = true;
         NhanVien v;
         if(this.rbchuyenvien.isSelected()){
             String cv = this.tfcongviec.getText();
             v = new ChuyenVien(cv,ma,ht,hsl,nvl,phai);
             ds.them(v);
             dm.addRow(new Object[]{v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),
               v.getNgayVaoLam(),v.isPhai(), ((ChuyenVien)v).getCongViec()});
         }
         else{
             String cvu = this.tfchucvu.getText();
             double pccv = Double.parseDouble(this.tfphucapchucvu.getText());
             v = new CanBoQuanLy (cvu,pccv,ma,ht,hsl,nvl,phai);            
             ds.them(v);
             dm.addRow(new Object[]{v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),
             v.getNgayVaoLam(),v.isPhai(),
                "",((CanBoQuanLy)v).getChucVu(),((CanBoQuanLy)v).getPhuCapChucVu()});
         }
        
        
    }//GEN-LAST:event_btthemActionPerformed

    private void bthienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthienthiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Danh sách nhân viên: \n" + ds.hienThi());
    }//GEN-LAST:event_bthienthiActionPerformed

    private void bttrungbinhluonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttrungbinhluonActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Trung bình lương: " + ds.trungBinhLuong());
    }//GEN-LAST:event_bttrungbinhluonActionPerformed

    private void bttimmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimmaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Nhân viên có mã cần tìm là: " + ds.tim(this.tfmanhanvien.getText()));
    }//GEN-LAST:event_bttimmaActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        String ma = this.tfmanhanvien.getText();
        String ht = this.tfhoten.getText();
        double hsl = Double.parseDouble(this.tfhesoluong.getText());
        Date nvl = new Date();
        DateFormat df = new SimpleDateFormat ("yyyy/m/d");
         try {
             nvl = df.parse(this.tfngayvaolam.getText());
         } catch (ParseException ex) {}
         boolean phai = true;
         if (this.rbnu.isSelected())
             phai = false;
         NhanVien v;
         //int i = this.jTable1.getSelectedRow();
         if(this.rbchuyenvien.isSelected()){
             String cv = this.tfcongviec.getText();
             v = new ChuyenVien(cv,ma,ht,hsl,nvl,phai);
             int i = this.jTable1.getSelectedRow();
             ds.sua(i, v);
             dm.removeRow(i);
             dm.insertRow(i, new Object[]{v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),
             df.format(v.getNgayVaoLam()),v.isPhai(), ((ChuyenVien)v).getCongViec()});
         }
         else{
             String cvu = this.tfchucvu.getText();
             double pccv = Double.parseDouble(this.tfphucapchucvu.getText());
             v = new CanBoQuanLy (cvu,pccv,ma,ht,hsl,nvl,phai); 
             int i = this.jTable1.getSelectedRow();
             ds.sua(i, v);
             dm.removeRow(i);
             dm.insertRow(i,new Object[]{v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),
             df.format(v.getNgayVaoLam()),v.isPhai(),
                "",((CanBoQuanLy)v).getChucVu(),((CanBoQuanLy)v).getPhuCapChucVu()});
         } 
    }//GEN-LAST:event_btsuaActionPerformed

    private void bttimphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimphaiActionPerformed
        // TODO add your handling code here:
        if(this.rbnam.isSelected())
            JOptionPane.showMessageDialog(this,"Phái của nhân viên là: "+ ds.timPhai(true));
        else
            JOptionPane.showMessageDialog(this,"Phái của nhân viên là: "+ ds.timPhai(false));
        
    }//GEN-LAST:event_bttimphaiActionPerformed

    private void btxoamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoamaActionPerformed
        // TODO add your handling code here:
        /*int i = ds.xoaNV(this.tfmanhanvien.getText());
        if (i != -1)
            dm.removeRow(i);*/
    }//GEN-LAST:event_btxoamaActionPerformed

    private void btxoadongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoadongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxoadongActionPerformed

    private void bttimmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttimmaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthienthi;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton bttimma;
    private javax.swing.JButton bttimmax;
    private javax.swing.JButton bttimphai;
    private javax.swing.JButton bttrungbinhluon;
    private javax.swing.JButton btxoadong;
    private javax.swing.JButton btxoama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbcanboquanly;
    private javax.swing.JRadioButton rbchuyenvien;
    private javax.swing.JRadioButton rbnam;
    private javax.swing.JRadioButton rbnu;
    private javax.swing.JTextField tfchucvu;
    private javax.swing.JTextField tfcongviec;
    private javax.swing.JTextField tfhesoluong;
    private javax.swing.JTextField tfhoten;
    private javax.swing.JTextField tfmanhanvien;
    private javax.swing.JTextField tfngayvaolam;
    private javax.swing.JTextField tfphucapchucvu;
    // End of variables declaration//GEN-END:variables

}
